from enum import Enum


class Code(Enum):
    CODE_ANALOG = 'CODE_ANALOG'
    CODE_DIGITAL = 'CODE_DIGITAL'
    CODE_CUSTOM = 'CODE_CUSTOM'
    CODE_LIMITSET = 'CODE_LIMITSET'
    CODE_SINGLENOE = 'CODE_SINGLENOE'
    CODE_MULTIPLENODE = 'CODE_MULTIPLENODE'
    CODE_CONSUMER = 'CODE_CONSUMER'
    CODE_SOURCE = 'CODE_SOURCE'
